### ISSUE TITLE
导入后报错

### ISSUE THREAD

**Issue by c82531** [With-Sky/HyperInt#1]
导入hpp文件后显示有多个构造函数 "HyperInt::HyperInt" 的实例与参数列表匹配...
请问怎么解决呢

**Comment by With-Sky** [comment]
可以看一下主文件的代码吗

**Comment by c82531** [comment]
hpp里就报错了诶

**Comment by With-Sky** [comment]
我这边是正常的，报错的完整信息提供一下吧，我修改一下

**Comment by c82531** [comment]
1194：HyperInt input_inv = 1;
报错：
多个构造函数应用于从 "int" 到 "HyperInt" 的转换: C/C++(416)
hint.hpp(1194, 30): 函数 "HyperInt::HyperInt(uint64_t input)" (已声明 所在行数:1577)
hint.hpp(1194, 30): 函数 "HyperInt::HyperInt(int64_t input)" (已声明 所在行数:1587)

1883：return HyperInt(static_cast<UINT_32>(sqrt(first_int32())));
报错：
inline HyperInt::HyperInt(uint32_t input)
还有 9 个重载
有多个构造函数 "HyperInt::HyperInt" 的实例与参数列表匹配:C/C++(309)
hint.hpp(1883, 20): 函数 "HyperInt::HyperInt(uint64_t input)" (已声明 所在行数:1577)
hint.hpp(1883, 20): 函数 "HyperInt::HyperInt(int64_t input)" (已声明 所在行数:1587)
hint.hpp(1883, 20): 参数类型为: (uint32_t)

还有一些也是类似的

**Comment by With-Sky** [comment]
感谢，我会尽快修改的

**Comment by c82531** [comment]
辛苦啦

**Comment by With-Sky** [comment]
我创建了一个分支，把修改后的文件提交到分支里了，你可以下载分支里的文件试试，如果还报错的话可以留言。

**Comment by With-Sky** [comment]
现在在做一个比较大的更新，再把你发现的bug修复以后就会发布了，到时候可以跟进一下。

**Comment by c82531** [comment]
还有一些
hint.hpp:1598:5: error: ‘HyperInt::HyperInt(long unsigned int)’ cannot be overloaded with ‘HyperInt::HyperInt(uint64_t)’
 1598 |     HyperInt(ULONG input) // unsigned long 参数构造
      |     ^~~~~~~~
hint.hpp:1577:5: note: previous declaration ‘HyperInt::HyperInt(uint64_t)’
 1577 |     HyperInt(UINT_64 input) // UINT_64 参数构造
      |     ^~~~~~~~
hint.hpp:1608:5: error: ‘HyperInt::HyperInt(long int)’ cannot be overloaded with ‘HyperInt::HyperInt(int64_t)’
 1608 |     HyperInt(LONG input) // long 参数构造
      |     ^~~~~~~~
hint.hpp:1587:5: note: previous declaration ‘HyperInt::HyperInt(int64_t)’
 1587 |     HyperInt(INT_64 input) // INT_64 参数构造
      |     ^~~~~~~~
hint.hpp:1700:15: error: ‘HyperInt& HyperInt::operator=(long unsigned int)’ cannot be overloaded with ‘HyperInt& HyperInt::operator=(uint64_t)’
 1700 |     HyperInt &operator=(ULONG input) // unsigned long 赋值
      |               ^~~~~~~~
hint.hpp:1677:15: note: previous declaration ‘HyperInt& HyperInt::operator=(uint64_t)’
 1677 |     HyperInt &operator=(UINT_64 input) // UINT_64 赋值
      |               ^~~~~~~~
hint.hpp:1711:15: error: ‘HyperInt& HyperInt::operator=(long int)’ cannot be overloaded with ‘HyperInt& HyperInt::operator=(int64_t)’
 1711 |     HyperInt &operator=(LONG input) // long 赋值
      |               ^~~~~~~~
hint.hpp:1688:15: note: previous declaration ‘HyperInt& HyperInt::operator=(int64_t)’
 1688 |     HyperInt &operator=(INT_64 input) // INT_64 赋值
      |               ^~~~~~~~
c8@LAPTOP-8LQFQ27F:/mnt/d/cpp/project2$ g++ main.cpp
In file included from main.cpp:7:
hint.hpp:1598:5: error: ‘HyperInt::HyperInt(long unsigned int)’ cannot be overloaded with ‘HyperInt::HyperInt(uint64_t)’
 1598 |     HyperInt(ULONG input) // unsigned long 参数构造
      |     ^~~~~~~~
hint.hpp:1577:5: note: previous declaration ‘HyperInt::HyperInt(uint64_t)’
 1577 |     HyperInt(UINT_64 input) // UINT_64 参数构造
      |     ^~~~~~~~
hint.hpp:1608:5: error: ‘HyperInt::HyperInt(long int)’ cannot be overloaded with ‘HyperInt::HyperInt(int64_t)’
 1608 |     HyperInt(LONG input) // long 参数构造
      |     ^~~~~~~~
hint.hpp:1587:5: note: previous declaration ‘HyperInt::HyperInt(int64_t)’
 1587 |     HyperInt(INT_64 input) // INT_64 参数构造
      |     ^~~~~~~~
hint.hpp:1700:15: error: ‘HyperInt& HyperInt::operator=(long unsigned int)’ cannot be overloaded with ‘HyperInt& HyperInt::operator=(uint64_t)’
 1700 |     HyperInt &operator=(ULONG input) // unsigned long 赋值
      |               ^~~~~~~~
hint.hpp:1677:15: note: previous declaration ‘HyperInt& HyperInt::operator=(uint64_t)’
 1677 |     HyperInt &operator=(UINT_64 input) // UINT_64 赋值
      |               ^~~~~~~~
hint.hpp:1711:15: error: ‘HyperInt& HyperInt::operator=(long int)’ cannot be overloaded with ‘HyperInt& HyperInt::operator=(int64_t)’
 1711 |     HyperInt &operator=(LONG input) // long 赋值
      |               ^~~~~~~~
hint.hpp:1688:15: note: previous declaration ‘HyperInt& HyperInt::operator=(int64_t)’
 1688 |     HyperInt &operator=(INT_64 input) // INT_64 赋值

**Comment by c82531** [comment]
还有一些
hint.hpp:1598:5: error: ‘HyperInt::HyperInt(long unsigned int)’ cannot be overloaded with ‘HyperInt::HyperInt(uint64_t)’
1598 | HyperInt(ULONG input) // unsigned long 参数构造
| ^~~~~~~~
hint.hpp:1577:5: note: previous declaration ‘HyperInt::HyperInt(uint64_t)’
1577 | HyperInt(UINT_64 input) // UINT_64 参数构造
| ^~~~~~~~
hint.hpp:1608:5: error: ‘HyperInt::HyperInt(long int)’ cannot be overloaded with ‘HyperInt::HyperInt(int64_t)’
1608 | HyperInt(LONG input) // long 参数构造
| ^~~~~~~~
hint.hpp:1587:5: note: previous declaration ‘HyperInt::HyperInt(int64_t)’
1587 | HyperInt(INT_64 input) // INT_64 参数构造
| ^~~~~~~~
hint.hpp:1700:15: error: ‘HyperInt& HyperInt::operator=(long unsigned int)’ cannot be overloaded with ‘HyperInt& HyperInt::operator=(uint64_t)’
1700 | HyperInt &operator=(ULONG input) // unsigned long 赋值
| ^~~~~~~~
hint.hpp:1677:15: note: previous declaration ‘HyperInt& HyperInt::operator=(uint64_t)’
1677 | HyperInt &operator=(UINT_64 input) // UINT_64 赋值
| ^~~~~~~~
hint.hpp:1711:15: error: ‘HyperInt& HyperInt::operator=(long int)’ cannot be overloaded with ‘HyperInt& HyperInt::operator=(int64_t)’
1711 | HyperInt &operator=(LONG input) // long 赋值
| ^~~~~~~~
hint.hpp:1688:15: note: previous declaration ‘HyperInt& HyperInt::operator=(int64_t)’
1688 | HyperInt &operator=(INT_64 input) // INT_64 赋值
| ^~~~~~~~

**Comment by With-Sky** [comment]
能提供一下你的开发环境吗，就是用什么编译器，我方便复原一下

**Comment by With-Sky** [comment]
这似乎不是完整的报错信息？我需要更多报错的信息

**Comment by c82531** [comment]
是用的vscode

**Comment by With-Sky** [comment]
编译器是什么呢，mingw64吗

**Comment by With-Sky** [comment]
在cmd命令行输入g++ -v
会显示编译器信息，最后一行是版本号，可以提供一下吗，我的是这样的
gcc version 12.1.0 (x86_64-posix-seh-rev3, Built by MinGW-W64 project)

**Comment by c82531** [comment]
gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1) 是这个

**Comment by With-Sky** [comment]
明白了，我待会上传一个更新的版本，谢谢你帮忙测试了

**Comment by With-Sky** [comment]
我把文件提交到了分支里，没有问题的话就合并到main了

**Comment by c82531** [comment]
ok的！请问是还不支持浮点数吗

**Comment by With-Sky** [comment]
最近只优化了和十进制字符串之间的转换。浮点数暂时没有弄，但是自己用的话可以通过一些技巧让它表现得和浮点数一样，可以参考源码里的牛顿迭代法除法
