### ISSUE TITLE
问题：无法使用多线程

### ISSUE THREAD

**Issue by SupJoN** [With-Sky/HyperInt#4]
取消对宏MULTITHREAD后vscode显示future为“不允许使用不完整的类型”，且无法成功编译

平台：windows 10
编译器：gcc 12.2.0 (x86_64-win32-seh-rev2, Built by MinGW-W64 project)
附加命令：-Wall -Wextra -std=c++20

**Comment by With-Sky** [comment]
你好，我这里编译没有问题，也许是编译器版本的问题，
操作系统：Windows 10 家庭中文版 22H2
编译器：gcc version 12.1.0 (x86_64-posix-seh-rev3, Built by MinGW-W64 project)

我现在在重构这个项目，如果无法解决但依然想用高精度计算的话可以试试我另一个仓库的项目
https://github.com/With-Sky/HyperInt-mini
这个项目只实现了四则运算，没有使用多线程，但运行速度可以达到原来HyperInt开启多线程速度，可以尝试一下。

**Comment by SupJoN** [comment]
好的，谢谢
